version: '3.8'

services:
  # MySQL база данных
  mysql:
    image: mysql:8.0
    container_name: infbez-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: labainfsec
      MYSQL_USER: webuser
      MYSQL_PASSWORD: QWErty!@#123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - infbez-network
    command: --default-authentication-plugin=mysql_native_password

  # Приложение
  app:
    image: deviantike/simple-webapp:1.0
    container_name: infbez-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=webuser
      - DB_PASSWORD=QWErty!@#123
      - DB_NAME=labainfsec
      - SESSION_SECRET=your-secret-key-change-this
    depends_on:
      - mysql
    networks:
      - infbez-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  infbez-network:
    driver: bridge
